# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(500, 300)
        login.setMinimumSize(QtCore.QSize(500, 300))
        login.setMaximumSize(QtCore.QSize(500, 300))
        self.login_register_btn = QtWidgets.QPushButton(login)
        self.login_register_btn.setGeometry(QtCore.QRect(20, 250, 93, 28))
        self.login_register_btn.setObjectName("login_register_btn")
        self.login_login_btn = QtWidgets.QPushButton(login)
        self.login_login_btn.setGeometry(QtCore.QRect(160, 230, 191, 41))
        self.login_login_btn.setObjectName("login_login_btn")
        self.graphicsView = QtWidgets.QGraphicsView(login)
        self.graphicsView.setGeometry(QtCore.QRect(20, 20, 111, 121))
        self.graphicsView.setStyleSheet("border-image: url(:/image/image/loginimage.jpg);\n"
"border-color: rgb(255, 255, 255);")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(login)
        self.label.setGeometry(QtCore.QRect(200, 30, 141, 51))
        self.label.setStyleSheet("font: 24pt \"Bahnschrift Condensed\";")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(login)
        self.widget.setGeometry(QtCore.QRect(150, 110, 211, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_username_text = QtWidgets.QLineEdit(self.widget)
        self.login_username_text.setObjectName("login_username_text")
        self.verticalLayout.addWidget(self.login_username_text)
        self.login_password_text = QtWidgets.QLineEdit(self.widget)
        self.login_password_text.setObjectName("login_password_text")
        self.verticalLayout.addWidget(self.login_password_text)

        self.retranslateUi(login)
        self.login_register_btn.clicked.connect(login.login_to_register)
        self.login_login_btn.clicked.connect(login.check_login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Form"))
        self.login_register_btn.setText(_translate("login", "注册"))
        self.login_login_btn.setText(_translate("login", "登入"))
        self.label.setText(_translate("login", "TestGUI"))
import ui_resource_rc
